### ISSUE TITLE
As a user, I want pixieapp to be able to display markdown notes

### ISSUE THREAD

**Issue by sihong-ma** [pixiedust/pixiegateway#15]
When I apply the following function in Pixieapp, I found that the markdown section couldn't be displayed:

from IPython.display import display, display_markdown
display_markdown("# Benchmark Run Group Overview:", raw=True)

**Comment by DTAIEB** [comment]
Fixed with PR https://github.com/ibm-watson-data-lab/pixiedust/pull/542
