### ISSUE TITLE
As a user, I want to view the apps so that i can view a list and select the app i wish to see

### ISSUE THREAD

**Issue by Arkoprabho** [pixiedust/pixiegateway#29]
### Expected behavior
http://server-ip:port/pixieapps should let me review and use the apps
### Actual behaviour
Takes me to a sign in page and asks for User Id and password.

**Comment by Arkoprabho** [comment]
Sample screenshot
![screenshot from 2018-11-02 09-54-50](https://user-images.githubusercontent.com/16442535/47893877-5f8ea280-de85-11e8-9669-66c5eedf8f26.png)

**Comment by DTAIEB** [comment]
The default userid is admin and default password is "" (blank). You can change these values via standard jupyter settings if running locally or through deployment.yaml if running on a kubernetes cluster.
Bear in mind that the pixieapps page is part of the pixiegateway admin console and therefore must be protected. If you are looking for a user facing page that list all the deployed pixieapps, then you can always create it yourself and associate it with the url of your choice via standard tornado mechanism.

**Comment by Arkoprabho** [comment]
Thank you for the reply. I was able to access the pixieapps. Another issue I faced once I was here was that delete didn't seem to work. Any pointers @DTAIEB
